include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - always_declare_return_types
    - avoid_empty_else
    - avoid_relative_lib_imports
    - avoid_returning_null_for_future
    - avoid_unused_constructor_parameters
    - prefer_const_constructors
    - prefer_final_fields
    - sized_box_for_whitespace
    - unnecessary_await_in_return
    - use_key_in_widget_constructors